Private events feature
Jarfsoft/private-events pull request #1
Opened 2021-02-03 20:29 UTC by Jarfsoft

**Features added:**
- Create new profile
- Sign in
- Create events
- Attend event
- Edit and delete profile

2021-02-04 00:04 UTC, oloomoses requested changes
# Status: Changes required
Hello team, you are doing great on this project
kindly implement the changes below before submitting another review

- [x] check that there is a link to the event show page
- [ ] Ensure that the event's show page displays the list of attendants 
- [ ] Add unit tests for the models
- [ ] Also remember to fix the logout. it is breaking

##### UsersController
###### `show` action
* [ ] lists events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))
* [ ] lists upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))

Feel free to reach me on slack [Oloo Moses]
Oloo Moses

2021-02-04 00:04 UTC, oloomoses commented on app/models/user.rb
> +end
Remember to delete all the commented code

2021-02-04 23:58 UTC, enaburekhan requested changes
# Status: Request changes:full_moon:
**Hi team!
Great job on implementing the changes requested by the previous Tse :clap::clap:. However, we just need to make a few changes to get this project approved :muscle:.**
**Mandatory changes**

- [ ] an index for the creator_id column is added to the events table. This is missing in the event table. Kindly fix this by creating and adding the migrations.

- [ ] the events_attendation/events_users/(any other name for join table between users and events) table has column `user_id` of type `integer`. This is also missing. Kindly add it

- [ ] an index for `user_id` column is added. Also, add this.

[Optional ]
  - Make the UI more user-friendly by styling it. 
  
Make the requested changes and when you are done, kindly request for another review.

You can reach me on slack @ Eric Enaburekhan if you have any questions.
Happy Coding:blush:
Eric Enaburekhan

2021-02-05 23:02 UTC, abredi requested changes
### Status: Require changes 🌳 ♲
Hi @Jarfsoft, I am  [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏   I appreciate your hard work. Kindly fix the following issues. 

[REQUIRED]

- [ ] The project misses the edit.html file in the events view/folder.

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

2021-02-07 19:01 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:
#### You can merge !!!

2021-02-08 14:07 UTC, merged